#!/usr/bin/env bash
# Install the pre-commit hook for this clone.
#
# The straightforward path is `pre-commit install`. It refuses to run when
# git's `core.hooksPath` is set globally -- some orgs point that at a secret
# scanner (ggshield, for example). Those wrappers typically call the repo's
# own .git/hooks/pre-commit as well, so the fix is to write that file
# ourselves rather than to unset anyone's global config.
set -euo pipefail

MARKER='File generated by pre-commit'

if uv run pre-commit install; then
    exit 0
fi

hooks_path="$(git config --get core.hooksPath || true)"
if [ -z "$hooks_path" ]; then
    echo "error: pre-commit install failed for a reason other than core.hooksPath." >&2
    exit 1
fi

echo
echo "pre-commit install refused: core.hooksPath is set to"
echo "  $hooks_path"
echo "Leaving that alone and writing this repo's hook directly instead."

# Note: `git rev-parse --git-path hooks` honours core.hooksPath and would point
# straight back at the wrapper, so resolve the repo's own hooks dir instead.
hooks_dir="$(git rev-parse --git-dir)/hooks"
mkdir -p "$hooks_dir"
hook="$hooks_dir/pre-commit"

if [ -e "$hook" ] && ! grep -q "$MARKER" "$hook"; then
    echo "error: $hook already exists and was not generated by pre-commit." >&2
    echo "Refusing to overwrite it. Merge the two by hand." >&2
    exit 1
fi

# Render pre-commit's own hook template so this tracks the installed version
# instead of hard-coding a copy that silently goes stale.
uv run python - "$hook" <<'PY'
import os
import stat
import sys
from pathlib import Path

import pre_commit.resources

hook = Path(sys.argv[1])
tmpl = (Path(pre_commit.resources.__file__).parent / "hook-tmpl").read_text()

lines = tmpl.splitlines(keepends=True)
start = lines.index("# start templated\n")
end = lines.index("# end templated\n")
lines[start + 1 : end] = [
    f"INSTALL_PYTHON={sys.executable!r}\n",
    "ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)\n",
]

hook.write_text("".join(lines))
hook.chmod(hook.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
print(f"wrote {hook}")
PY

# The wrapper only runs our hook if it actually delegates. Warn if it doesn't.
wrapper="$hooks_path/pre-commit"
if [ -f "$wrapper" ] && ! grep -q 'hooks/pre-commit' "$wrapper"; then
    echo
    echo "warning: $wrapper does not appear to call .git/hooks/pre-commit," >&2
    echo "so the hooks in .pre-commit-config.yaml may never run. Verify with a" >&2
    echo "throwaway commit before trusting nbstripout to strip notebook output." >&2
fi
